export const images = {
  ADA: '../Images/ADA.PNG',
  BCH: '../Images/BCH.PNG',
  BNB: '../Images/BCH.PNG',
  BTC: '../Images/BTC.PNG',
  DASH: '../Images/DASH.PNG',
  EOS: '../Images/EOS.PNG',
  ETC: '../Images/ETC.PNG',
  ETH: '../Images/ETH.PNG',
  MIOTA: '../Images/IOTA.PNG',
  LTC: '../Images/LTC.PNG',
  NEM: '../Images/NEM.PNG',
  NEO: '../Images/NEO.PNG',
  QTUM: '../Images/QTUM.PNG',
  TRX: '../Images/TRX.PNG',
  USDT: '../Images/USDT.PNG',
  VEN: '../Images/VEN.PNG',
  XLM: '../Images/XLM.PNG',
  XMR: '../Images/XMR.PNG',
  XRP: '../Images/XRP.PNG',
}